name: Deployment
run-name: Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ“¦ Deployment has started."
      - run: pnpm run deploy
      - run: echo "ğŸ‰ Successfully deployed!"