name: Deployment
run-name: Deployment
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.2.4
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ“¦ Deployment has started."
      - run: pnpm run deploy
      - run: echo "ğŸ‰ Successfully deployed!"