name: New Pull Request
run-name: New Pull Request
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸ¤¯ New pull request!"
      - run: pnpm run lint:js && pnpm run lint:css && pnpm run build && pnpm run analyze
      - run: echo "ðŸŽ‰ Successfully done something!"